// src/components/Footer.vue
<template>
  <footer class="footer has-text-centered">
    <div class="content">
      <p>
        <img src="@/assets/img/aiko.png" alt="Logo" class="logo" /><br> &copy; 2024 - Todos os direitos
        reservados.<br />
        teste/Alexandre Pedro Rodrigues
      </p>
    </div>
  </footer>
</template>

<style scoped>
.footer {
  padding: 1rem 1.5rem;
  background-color: #ffffff;
  color: #555; 
  font-size: 10px;
}
.logo {
  width: 40px;
  height: auto;
}
</style>

// my-app/src/components/Footer/index.tsx
"use client";

import Image from 'next/image';
import styles from './Footer.module.css';
import Logo from '@/public/aiko.png';

export default function Footer() {
  return (
    <footer className={styles.footer}>
      <Image src={Logo} alt="" width={28} height={22} />
      <p>Aiko. Alguns direitos reservados</p>
    </footer>
  );
}
