// projeto-front-end/src/pages/Home.tsx
import { useNavigate } from 'react-router-dom';
import Img from '../assets/img.jpg';
import Logo from '../../../img/aiko.png';
import ImgBack from '../assets/IMG-Home.png'

function Home() {
  // Create a navigate function
  const navigate = useNavigate();

  return (
    <div
      className="w-full h-screen bg-cover bg-center flex flex-col justify-between"
      style={{ backgroundImage: `url(${Img})` }}
    >
      <div className="p-5 justify-center">
        <img src={Logo} alt="Logo Aiko" className="w-32 m-auto" />
      </div>

      <div className="flex flex-1 flex-col lg:flex-row items-center justify-center w-3/4 m-auto">
        <div className="lg:w-1/2 w-full flex flex-col items-center text-center px-4 lg:px-16">
          <h1 className="text-3xl lg:text-4xl font-bold text-blue-800">Monitoramento</h1>
          <h2 className="text-4xl lg:text-6xl font-extrabold text-white mt-2">FLORESTAL</h2>
          <p className="text-blue-700 text-base lg:text-lg mt-4">
            Monitoramento de Equipamentos Florestais: Posições e Estados Operacionais
          </p>
          <button 
            className="mt-6 bg-gradient-to-r from-blue-300 to-blue-500 text-blue-800 font-bold px-10 py-3 rounded-full shadow-lg hover:bg-gradient-to-r hover:from-blue-400 hover:to-blue-600 transition duration-300 shadow-white"
            onClick={() => navigate('/painel')} // Navigate to Painel page
          >
            Acessar Painel
          </button>
        </div>

        <div className="lg:w-1/2 w-full flex justify-center mt-6 lg:mt-0">
          <img src={ImgBack} alt="Monitoramento" className="w-72 lg:w-3/4" />
        </div>
      </div>

      <div className="text-center text-lg text-gray-600 mb-4 justify-center m-auto">
        <p>Design by | Rennan Alves</p>
      </div>
    </div>
  );
}

export default Home;

// vue-app/src/pages/Home.vue
<template>
  <section class="flex items-center justify-center w-full h-full home-section">
    <div class="flex flex-col gap-4">
      <div class="flex items-center">
        <img src="@/assets/img/dodo-logo.png" alt="doodo" width="100">
        <span class="text-2xl font-bold text-zinc-200">Dodo</span>
        <span class="text-2xl font-bold text-green-700">Agro</span>
      </div>
      <Button class="shadow-md shadow-zinc-800 hover:bg-zinc-800">
        Entrar
      </Button>
    </div>
  </section>
</template>
<script lang="ts">
import { defineComponent } from "vue";
import Button from "@/components/ui/button/Button.vue" ;
export default defineComponent({
  components: {
    Button,
  },
});
</script>
<style scoped>
.home-section {
  background-image: url("@/assets/img/background.png");
  background-size: cover;
  background-position: center;
}
</style>
