// src/components/MapView.tsx
import { useEffect, useState } from 'react'
import { MapContainer, TileLayer } from 'react-leaflet'
import EquipmentMarker from './EquipmentMarker'
import EquipmentDetails from './EquipmentDetails'
import type { Equipment, MapViewProps } from '../types/Equipment'
import positionHistory from '../data/equipmentPositionHistory.json'
import { getLatestPosition } from '../utils/dataUtils'
import 'leaflet/dist/leaflet.css'

export default function MapView({ equipmentList }: MapViewProps) {
  const [equipmentWithPosition, setEquipmentWithPosition] = useState<
    Equipment[]
  >([])
  const [selectedEquipmentId, setSelectedEquipmentId] = useState<string | null>(
    null
  )

  useEffect(() => {
    const updatedEquipmentList = equipmentList.map((equipment) => {
      const latestPosition = getLatestPosition(equipment.id, positionHistory)
      return {
        ...equipment,
        position: latestPosition
          ? { lat: latestPosition.lat, lng: latestPosition.lon }
          : equipment.position,
      }
    })

    setEquipmentWithPosition(updatedEquipmentList)
  }, [equipmentList])

  const handleMarkerClick = (equipment: Equipment) => {
    setSelectedEquipmentId(equipment.id)
  }

  return (
    <div style={{ display: 'flex' }}>
      <MapContainer
        center={[-19.1, -46]}
        zoom={11}
        style={{ height: '100vh', width: '100%' }}
      >
        <TileLayer
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
          attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        />
        {equipmentWithPosition.map((equipment) => (
          <EquipmentMarker
            key={equipment.id}
            equipment={equipment}
            onClick={() => handleMarkerClick(equipment)}
          />
        ))}
      </MapContainer>
      {selectedEquipmentId && (
        <div style={{ width: '20%', padding: '20px' }}>
          <EquipmentDetails equipmentId={selectedEquipmentId} />
        </div>
      )}
    </div>
  )
}

// src/app/pages/map-view/map-view.component.ts
import { Component, OnInit } from '@angular/core';
import * as L from 'leaflet';
import data from '../../../assets/data/equipmentPositionHistory.json'

interface Position {
  date: string;
  lat: number;
  lon: number;
}

interface Equipment {
  equipmentId: string;
  positions: Position[];
}

@Component({
  selector: 'app-map-view',
  standalone: true,
  imports: [],
  templateUrl: './map-view.component.html',
  styleUrls: ['./map-view.component.css']
})
export class MapViewComponent implements OnInit {

  private equipamentPositions: any = data;

  ngOnInit(): void {
    this.initMap();
  }

  private initMap(): void {
    let config = {
      minZoom: 10,
      maxZoom: 17,
    };
    const zoom = 9;

    const lat = -19.231295;
    const lng = -46.104467;

    const map = L.map("map", config).setView([lat, lng], zoom);

    L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png", {
      attribution:
        '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
    }).addTo(map);

    this.displayEquipmentMarkers(map);
  }

  private displayEquipmentMarkers(map: L.Map): void {
    this.equipamentPositions.forEach((equipment: Equipment) => {
      const latestPosition = this.getLatestPosition(equipment.positions);

      if (latestPosition) {
        const marker = L.marker([latestPosition.lat, latestPosition.lon]).addTo(map);
        marker.bindPopup(`<b>Equipment ID:</b> ${equipment.equipmentId}<br><b>Date:</b> ${latestPosition.date}`);
      }
    });
  }

  private getLatestPosition(positions: Position[]): Position | undefined {
    if (!positions || positions.length === 0) {
      return undefined;
    }

    return positions.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())[0];
  }
}

<div id="map" (click)="onMapClick($event)"></div>

<app-equipment-history *ngIf="sidebarVisible" [equipment]="selectedEquipment"></app-equipment-history>
