// src/app/pages/map-view/map-view.component.ts
import { Component, OnInit } from '@angular/core';
import * as L from 'leaflet';
import positions from '../../../assets/data/equipmentPositionHistory.json'
import states from '../../../assets/data/equipmentStateHistory.json'
import stateInfo from '../../../assets/data/equipmentState.json'

interface Position {
  date: string;
  lat: number;
  lon: number;
}

interface Equipment {
  equipmentId: string;
  positions: Position[];
}

interface EquipmentState {
  equipmentId: string;
  states: {
    date: string;
    equipmentStateId: string;
  }[];
}

interface StateInfo {
  id: string;
  name: string;
  color: string;
}

@Component({
  selector: 'app-map-view',
  standalone: true,
  imports: [],
  templateUrl: './map-view.component.html',
  styleUrls: ['./map-view.component.css']
})
export class MapViewComponent implements OnInit {

  private equipamentPositions: any = positions;
  private equipmentStates: any = states;
  private stateInfo: any = stateInfo;

  ngOnInit(): void {
    this.initMap();
  }

  private initMap(): void {
    let config = {
      minZoom: 10,
      maxZoom: 17,
    };
    const zoom = 9;

    const lat = -19.231295;
    const lng = -46.104467;

    const map = L.map("map", config).setView([lat, lng], zoom);

    L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png", {
      attribution:
        '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
    }).addTo(map);

    this.displayEquipmentMarkers(map);
  }

  private displayEquipmentMarkers(map: L.Map): void {
    this.equipamentPositions.forEach((equipment: Equipment) => {
      const latestPosition = this.getLatestPosition(equipment.positions);
      const latestState = this.getLatestStateInfo(equipment.equipmentId);

      if (latestPosition && latestState) {
        const customIcon = L.divIcon({
          className: 'marker-icon',
          html: `<div style="background-color: ${latestState.color}; width: 24px; height: 24px; border-radius: 50%; border: 2px solid white;"></div>`,
        });

        const marker = L.marker([latestPosition.lat, latestPosition.lon], { icon: customIcon }).addTo(map);
        marker.bindPopup(
          `<b>Equipamento:</b> ${equipment.equipmentId}<br>
          <b>Data:</b> ${latestPosition.date}<br>
          <b>Estado:</b> ${latestState.name}`
        );
      }
    });
  }

  private getLatestPosition(positions: Position[]): Position | undefined {
    if (!positions || positions.length === 0) {
      return undefined;
    }

    return positions.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())[0];
  }

  private getLatestStateInfo(equipmentId: string): StateInfo | undefined {
    const equipmentState = this.equipmentStates.find((state: EquipmentState) => state.equipmentId === equipmentId);

    if (!equipmentState || equipmentState.states.length === 0) {
      return undefined;
    }

    const latestState = equipmentState.states.sort((a: { date: string | number | Date; }, b: { date: string | number | Date; }) => new Date(b.date).getTime() - new Date(a.date).getTime())[0];
    return this.stateInfo.find((info: StateInfo) => info.id === latestState.equipmentStateId);
  }
}

<div id="map" (click)="onMapClick($event)"></div>

<app-equipment-history *ngIf="sidebarVisible" [equipment]="selectedEquipment"></app-equipment-history>

// src/components/maps/MapView.vue
<template>
  <div class="h-full w-full p-2">
    <div id="map" class="h-full w-full"></div>
  </div>
</template>

<script setup lang="ts">
import { onMounted } from 'vue'
import L from 'leaflet'
import { formatDate } from '@/utils/format'
import { equipmentState } from '@/data/equipmentState'
import type {
  EquipmentPositionHistory,
  Positions,
  States,
  EquipmentState,
  Equipment,
  EquipmentStateHistory,
} from '@/types'
import { useEquipmentsStore } from '@/stores/equipments'
import { getLastKnown } from '@/utils/common'
import { useLoadingStore } from '@/stores/loading'

const storeEquipment = useEquipmentsStore()
const loadingStore = useLoadingStore()

const loadMap = async () => {
  const map = L.map('map').setView([-19.9208, -43.9378], 8)

  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    maxZoom: 19,
    attribution: '© OpenStreetMap contributors',
  }).addTo(map)

  storeEquipment.equipments.forEach((equipment: Equipment) => {
    const positions: EquipmentPositionHistory | undefined = storeEquipment.positions.find(
      (pos) => pos.equipmentId === equipment.id,
    )

    const state: EquipmentStateHistory | undefined = storeEquipment.states.find(
      (st) => st.equipmentId === equipment.id,
    )

    if (positions && state) {
      const lastKnownPosition: Positions | undefined = getLastKnown(positions.positions)
      const lastKnownState: States | undefined = getLastKnown(state.states)

      const equipmentState_: EquipmentState | undefined = equipmentState.find(
        (st) => st.id === lastKnownState?.equipmentStateId,
      )

      if (lastKnownPosition && lastKnownState) {
        const marker = L.marker([lastKnownPosition.lat, lastKnownPosition.lon])
        marker.addTo(map).bindPopup(
          `
    <div class="bg-white text-gray-800 text-center">
      <h3 class="font-bold text-lg">${equipment.name}</h3>
      <p class="text-sm"><strong>Última posición:</strong> ${formatDate(lastKnownPosition.date)}</p>
      <p class="text-sm"><strong>Estado:</strong> ${equipmentState_?.name}</p>
    </div>
    `,
        )
      }
    }
  })
}

onMounted(async () => {
  loadingStore.loading = true
  await storeEquipment.fetchEquipments()
  await storeEquipment.fetchPositions()
  await storeEquipment.fetchStates()
  await storeEquipment.fetchModels()
  await loadMap()
  loadingStore.loading = false
})
</script>

<style scoped></style>
