// src/components/EquipmentMap/EquipmentMap.tsx
import React, { useState, useEffect } from "react";
import { MapContainer, TileLayer, Marker, Popup } from "react-leaflet";
import "leaflet/dist/leaflet.css";
import L from "leaflet";
import equipmentData from "../../../data/equipment.json";
import equipmentPositionHistory from "../../../data/equipmentPositionHistory.json";
import equipmentState from "../../../data/equipmentState.json";
import equipmentStateHistory from "../../../data/equipmentStateHistory.json";
import equipmentModel from "../../../data/equipmentModel.json";
import Modal from "react-modal";
import "./EquipmentMap.scss";

Modal.setAppElement("#root");

interface Position {
  id: string;
  lat: number;
  lon: number;
}

interface State {
  id: string;
  name: string;
  color: string;
}

interface Model {
  id: string;
  name: string;
  hourlyEarnings: any[];
}

const EquipmentMap: React.FC = () => {
  const [positions, setPositions] = useState<Position[]>([]);
  const [equipmentStates, setEquipmentStates] = useState<any>({});
  const [stateHistory, setStateHistory] = useState<any>({});
  const [models, setModels] = useState<any>({});
  const [selectedEquipmentId, setSelectedEquipmentId] = useState<string | null>(null);
  const [selectedStateHistory, setSelectedStateHistory] = useState<any[]>([]);
  const [modalIsOpen, setModalIsOpen] = useState<boolean>(false);

  useEffect(() => {
    const latestPositions = equipmentPositionHistory.map((item: any) => {
      const lastPosition = item.positions[item.positions.length - 1];
      return {
        id: item.equipmentId,
        lat: lastPosition.lat,
        lon: lastPosition.lon,
      };
    });
    setPositions(latestPositions);

    const statesMap = equipmentState.reduce((acc: any, state: State) => {
      acc[state.id] = state;
      return acc;
    }, {});
    setEquipmentStates(statesMap);

    const stateHistoryMap = equipmentStateHistory.reduce((acc: any, history: any) => {
      acc[history.equipmentId] = history.states;
      return acc;
    }, {});
    setStateHistory(stateHistoryMap);

    const modelsMap = equipmentModel.reduce((acc: any, model: Model) => {
      acc[model.id] = model;
      return acc;
    }, {});
    setModels(modelsMap);
  }, []);

  useEffect(() => {
    if (selectedEquipmentId) {
      const history = stateHistory[selectedEquipmentId] || [];
      setSelectedStateHistory(history);
    } else {
      setSelectedStateHistory([]);
    }
  }, [selectedEquipmentId, stateHistory]);

  const getCurrentState = (equipmentId: string) => {
    const history = stateHistory[equipmentId];
    if (!history || history.length === 0) return null;
    const latestStateId = history[history.length - 1].equipmentStateId;
    return equipmentStates[latestStateId];
  };

  const getModelName = (modelId: string) => {
    return models[modelId]?.name || "Desconhecido";
  };

  const openModal = (equipmentId: string) => {
    setSelectedEquipmentId(equipmentId);
    setModalIsOpen(true);
  };

  const closeModal = () => {
    setModalIsOpen(false);
    setSelectedEquipmentId(null);
  };

  return (
    <div>
      <MapContainer
        center={[-19.126536, -45.947756]}
        zoom={10}
        style={{ height: "500px", width: "100%" }}
      >
        <TileLayer
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
          attribution="&copy; OpenStreetMap contributors"
        />
        {positions.map((pos) => {
          const currentState = getCurrentState(pos.id);
          const equipment = equipmentData.find((eq) => eq.id === pos.id);
          return (
            <Marker
              key={pos.id}
              position={[pos.lat, pos.lon]}
              eventHandlers={{
                click: () => openModal(pos.id),
              }}
              icon={L.divIcon({
                className: "custom-icon",
                html: `<div style="background-color: ${currentState?.color || "#000"};" class="icon"></div>`,
                iconSize: [25, 25],
              })}
            >
              <Popup>
                <div>
                  <h3>{equipment?.name || "Equipamento Desconhecido"}</h3>
                  <p>Modelo: {getModelName(equipment?.equipmentModelId || "")}</p>
                  {currentState && (
                    <p style={{ color: currentState.color }}>
                      Estado atual: {currentState.name}
                    </p>
                  )}
                </div>
              </Popup>
            </Marker>
          );
        })}
      </MapContainer>

      <Modal
        isOpen={modalIsOpen}
        onRequestClose={closeModal}
        contentLabel="Detalhes do Equipamento"
        className="modal"
        overlayClassName="overlay"
      >
        <h2>Detalhes do Equipamento</h2>
        {selectedEquipmentId && (
          <div>
            <h3>
              {equipmentData.find((eq) => eq.id === selectedEquipmentId)?.name || "Equipamento Desconhecido"}
            </h3>
            <p>
              Modelo: {getModelName(equipmentData.find((eq) => eq.id === selectedEquipmentId)?.equipmentModelId || "")}
            </p>
            <p>
              Estado atual: {getCurrentState(selectedEquipmentId)?.name || "Desconhecido"}
            </p>
            <h4>Histórico de Estados:</h4>
            <div className="state-history">
              {selectedStateHistory.length > 0 ? (
                <table>
                  <thead>
                    <tr>
                      <th>Data</th>
                      <th>Estado</th>
                    </tr>
                  </thead>
                  <tbody>
                    {selectedStateHistory.map((state: any, index: number) => (
                      <tr key={index}>
                        <td>{new Date(state.date).toLocaleString()}</td>
                        <td>
                          {equipmentStates[state.equipmentStateId]?.name || "Desconhecido"}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              ) : (
                <p>Sem histórico de estados disponível.</p>
              )}
            </div>
            <button className="close-button" onClick={closeModal}>
              Fechar
            </button>
          </div>
        )}
      </Modal>
    </div>
  );
};

export default EquipmentMap;

// src/pages/EquipmentMap.vue
<template>
  <q-page padding>
    <div style="height: 88vh; width: 100%">
      <l-map :zoom="zoom" :center="center" :useGlobalLeaflet="false">
        <l-tile-layer :url="url" />
        <div v-if="positionHistories.length > 0">
          <l-marker
            v-for="equipment in equipments"
            :key="equipment.id"
            :lat-lng="[
              getLatestPosition(equipment).lat,
              getLatestPosition(equipment).lon,
            ]"
            :icon="getIconForEquipment(equipment)"
          >
            <l-popup>
              <div>
                <p>
                  {{ getEquipmentModelName(equipment) }} - {{ equipment.name }}
                </p>
                <p>Estado: {{ getCurrentState(equipment).name }}</p>
                <q-btn
                  size="md"
                  class="q-pa-sm"
                  icon="mdi-clipboard-clock-outline"
                  @click="selectEquipment(equipment)"
                >
                  <q-tooltip>Histórico</q-tooltip>
                </q-btn>
              </div>
            </l-popup>
          </l-marker>
        </div>
      </l-map>
    </div>

    <q-dialog v-model="dialogVisible" max-width="500px">
      <EquipmentDetails
        :equipment="selectedEquipment"
        :states="states"
        :history="getEquipmentHistory(selectedEquipment)"
      />
    </q-dialog>
  </q-page>
</template>

<script setup>
import { ref, onMounted } from "vue";
import "leaflet/dist/leaflet.css";
import { LMap, LTileLayer, LPopup, LMarker } from "@vue-leaflet/vue-leaflet";
import EquipmentDetails from "./EquipmentDetails.vue";
import L from "leaflet";

const zoom = ref(5);
const center = ref([-19.126536, -45.947756]);
const url = "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png";

const equipments = ref([]);
const states = ref([]);
const models = ref([]);
const stateHistories = ref([]);
const positionHistories = ref([]);
const selectedEquipment = ref(null);
const dialogVisible = ref(false);


const loadJson = async (filename) => {
  try {
    const response = await fetch(`/data/${filename}`);
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    return await response.json();
  } catch (error) {
    console.error("Failed to load JSON:", error);
    throw error; // Re-throw error to be handled in mounted
  }
};

const getEquipmentModelName = (equipment) => {
  const model = models.value.find((m) => m.id === equipment.equipmentModelId);
  return model ? model.name : "Unknown Model";
};

const getLatestPosition = (equipment) => {
  console.log("histories", positionHistories.value);
  console.log("equipametno", equipment);
  const history = positionHistories.value.find(
    (h) => h.equipmentId === equipment.id
  );
  return history.positions[history.positions.length - 1];
};

const getCurrentState = (equipment) => {
  const history = stateHistories.value.find(
    (h) => h.equipmentId === equipment.id
  );
  const latestStateId =
    history.states[history.states.length - 1].equipmentStateId;
  return states.value.find((state) => state.id === latestStateId);
};

const getEquipmentHistory = (equipment) => {
  return stateHistories.value.find((h) => h.equipmentId === equipment.id);
};

const selectEquipment = (equipment) => {
  selectedEquipment.value = equipment;
  dialogVisible.value = true;
};

onMounted(async () => {
  equipments.value = await loadJson("equipment.json");
  states.value = await loadJson("equipmentState.json");
  models.value = await loadJson("equipmentModel.json");
  stateHistories.value = await loadJson("equipmentStateHistory.json");
  positionHistories.value = await loadJson("equipmentPositionHistory.json");
});
</script>
