// app/src/components/Map/index.tsx
"use client"

import React from 'react';
import { MapContainer, MapContainerProps, TileLayer } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import dynamic from 'next/dynamic';

interface Props extends MapContainerProps {
  children?: React.ReactNode
}

export function _Map({ children, ...props }: Props) {
  if (typeof window === 'undefined') return null

  return (
    <>
      <div
        id='map'
        className='w-full h-full shrink-0 rounded-md bg-gray-300 shadow-md'
      >
        <MapContainer
          style={{ flex: 1, width: '100%', height: 'calc(100vh - 65px)' }}
          center={{ lat: -22.637081990512296, lng: -54.823245482408126 }}
          zoom={12}
          {...props}
        >
          <TileLayer
            attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'
            url="https://tile.openstreetmap.org/{z}/{x}/{y}.png"
            className='!w-full !h-full'
          />
          {children}
        </MapContainer>
      </div >
    </>
  )
}

export const Map = dynamic(() => Promise.resolve(_Map), {
  ssr: false,
})

// aiko-front/src/components/Map.vue
<script lang="ts" setup>
import 'leaflet/dist/leaflet.css'
import L from 'leaflet'
import { onMounted } from 'vue'

let map = undefined

const createMapLayer = () => {
  map = L.map('mapContainer').setView([-19.126536, -45.947756], 9)
  L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
  }).addTo(map)
}

onMounted(() => {
  createMapLayer()
})
</script>

<template>
  <div id="mapContainer"></div>
</template>

<style scoped>
#mapContainer {
  height: 1000px;
  width: 1000px;
}
</style>
