// components/App/Header.vue
<script setup lang="ts">
</script>

<template>
  <header>
    <NuxtLink to="/">
      <img src="~/assets/aiko.png" alt="logo" />
    </NuxtLink>
    <nav>
      <NuxtLink to="/">Início</NuxtLink>
      <NuxtLink to="/map">Mapa</NuxtLink>
    </nav>
  </header>
</template>

<style scoped>
header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  background-color: white;
  padding: 16px 32px;

  img {
    height: 24px;
  }

  a {
    color: var(--primary-color);

    &:hover {
      color: var(--secondary-color);
    }
  }
}
</style>

// src/components/header/index.tsx
import Image from "next/image";

export default function Header() {
  return (
    <nav
      className="bg-white shadow text-white p-5 sm:p-2 md:flex md:justify-between 
    md:items-center"
    >
      <div className="container mx-auto flex justify-between items-center">
        <a href="/" className="flex items-center">
          <Image
            src="/img/aiko.png"
            alt="Logo"
            width={95}
            height={95}
            priority={true}
          />
        </a>
      </div>
    </nav>
  );
}
