// src/components/EquipmentMap.tsx
import React, { useState, useEffect } from 'react';
import { MapContainer, TileLayer, Marker, Popup } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import equipmentData from '../../data/equipment.json';
import equipmentPositionHistory from '../../data/equipmentPositionHistory.json';

const EquipmentMap: React.FC = () => {
  const [positions, setPositions] = useState<any[]>([]);

  useEffect(() => {
    const latestPositions = equipmentPositionHistory.map((item: any) => {
      const lastPosition = item.positions[item.positions.length - 1];
      return {
        id: item.equipmentId,
        lat: lastPosition.lat,
        lon: lastPosition.lon,
      };
    });
    setPositions(latestPositions);
  }, []);

  return (
    <MapContainer center={[-19.126536, -45.947756]} zoom={10} style={{ height: '500px', width: '100%' }}>
      <TileLayer
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
        attribution="&copy; OpenStreetMap contributors"
      />
      {positions.map((pos: any) => (
        <Marker key={pos.id} position={[pos.lat, pos.lon]}>
          <Popup>
            <div>
              <h3>{equipmentData.find((eq) => eq.id === pos.id)?.name}</h3>
              <p>Estado atual: Operando</p>
            </div>
          </Popup>
        </Marker>
      ))}
    </MapContainer>
  );
};

export default EquipmentMap;

// src/components/EquipmentMap.vue
<template>
    <div id="map" style="height: 400px"></div>
  </template>
  
  <script lang="ts">
  import { defineComponent, onMounted, PropType } from 'vue';
  import L from 'leaflet';
  import 'leaflet/dist/leaflet.css';
  
  // Define uma interface para a posição do equipamento
  interface EquipmentPosition {
    lat: number;
    lon: number;
    equipmentId: string; // Adicione qualquer outra propriedade que você estiver usando
  }
  
  export default defineComponent({
    name: 'EquipmentMap',
    props: {
      equipmentPositions: {
        type: Array as PropType<EquipmentPosition[]>,
        default: () => []
      }
    },
    setup(props) {
      onMounted(() => {
        const map = L.map('map').setView([0, 0], 2);
  
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
          attribution:
            '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
        }).addTo(map);
  
        // Adicione uma verificação para garantir que equipmentPositions não é vazio
        if (props.equipmentPositions && props.equipmentPositions.length) {
          props.equipmentPositions.forEach((position: EquipmentPosition) => {
            L.marker([position.lat, position.lon])
              .addTo(map)
              .bindPopup(`Equipment ID: ${position.equipmentId}`);
          });
        }
      });
    },
  });
  </script>
  
  <style scoped>
  #map {
    width: 100%;
    height: 400px;
  }
  </style>
