// components/EquipmentMap.vue
<script lang="ts" setup>
/** Data */
import eph from '~/data/equipmentPositionHistory.json';

/** Interfaces */
import type { IEquipmentPositionHistory } from '~/interfaces/IEquipmentPositionHistory';

const equipmentPositionHistory = ref<IEquipmentPositionHistory[]>(eph);
const zoom = ref(2);

function getLastPosition(positions: { lat: number; lon: number }[]) {
  return positions[positions.length - 1];
}
</script>

<template>
  <div>
    <LMap style="height: 700px" :zoom="zoom" :center="[47.21322, -1.559482]" :use-global-leaflet="false">
      <LTileLayer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
        attribution="&amp;copy; <a href=&quot;https://www.openstreetmap.org/&quot;>OpenStreetMap</a> contributors"
        layer-type="base" name="OpenStreetMap" />

      <div v-for="equipment in equipmentPositionHistory" :key="equipment.equipmentId">
        <LMarker :lat-lng="[getLastPosition(equipment.positions).lat, getLastPosition(equipment.positions).lon]">
          <LPopup>
            {{ equipment.equipmentId }}
          </LPopup>
        </LMarker>
      </div>
    </LMap>
  </div>
</template>

// src/components/EquipmentMap.tsx
import React, { useState, useEffect } from 'react';
import { MapContainer, TileLayer, Marker, Popup } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import equipmentData from '../../data/equipment.json';
import equipmentPositionHistory from '../../data/equipmentPositionHistory.json';

const EquipmentMap: React.FC = () => {
  const [positions, setPositions] = useState<any[]>([]);

  useEffect(() => {
    const latestPositions = equipmentPositionHistory.map((item: any) => {
      const lastPosition = item.positions[item.positions.length - 1];
      return {
        id: item.equipmentId,
        lat: lastPosition.lat,
        lon: lastPosition.lon,
      };
    });
    setPositions(latestPositions);
  }, []);

  return (
    <MapContainer center={[-19.126536, -45.947756]} zoom={10} style={{ height: '500px', width: '100%' }}>
      <TileLayer
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
        attribution="&copy; OpenStreetMap contributors"
      />
      {positions.map((pos: any) => (
        <Marker key={pos.id} position={[pos.lat, pos.lon]}>
          <Popup>
            <div>
              <h3>{equipmentData.find((eq) => eq.id === pos.id)?.name}</h3>
              <p>Estado atual: Operando</p>
            </div>
          </Popup>
        </Marker>
      ))}
    </MapContainer>
  );
};

export default EquipmentMap;
