// components/App/Header.vue
<script setup lang="ts">
</script>

<template>
  <header class="header">
    <NuxtLink to="/">
      <img src="~/assets/aiko.png" alt="logo" />
    </NuxtLink>
    <nav>
      <NuxtLink to="/">Home</NuxtLink>
      <NuxtLink to="/equipments">Equipamentos</NuxtLink>
    </nav>
  </header>
</template>

<style scoped>
.header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  background-color: white;
  padding: 16px;

  img {
    height: 24px;
  }

  nav {
    display: flex;
    gap: 24px;

    a {
      color: rgb(0, 51, 128);
      font-weight: bold;
      text-decoration: none;

      &:hover {
        color: rgb(0, 193, 0);
      }
    }
  }
}
</style>

// src/components/Header.tsx
import React from 'react';
import { Navbar, Container } from 'react-bootstrap';
import aikoImage from '../img/aiko.png';

const Header: React.FC = () => {
  return (
    <Navbar bg="dark" variant="dark">
      <Container className="d-flex justify-content-between">
        <Navbar.Brand href="#home" className="d-flex align-items-center">
          <img
            src={aikoImage}
            alt="Aiko"
            width="100"
            height="40"
            className="d-inline-block align-top"
          />
        </Navbar.Brand>

        <Navbar.Text className="ml-auto text-light">
          Desafio Frontend - Rastreamento de equipamentos
        </Navbar.Text>
      </Container>
    </Navbar>
  );
};

export default Header;
