// aiko-challenge/src/app/core/components/map/map.component.ts
import { Component, inject, Input, OnInit } from '@angular/core';
import * as LF from 'leaflet';
import { IPosition } from '../../interfaces/iPosition';
import { EquipmentService } from '../../services/equipment/equipment.service';
import { IEquipmentState } from '../../interfaces/iEquipmentState';
import { ICustomEquipment } from '../../interfaces/iCustomEquipment';

@Component({
  selector: 'app-map',
  standalone: true,
  imports: [],
  templateUrl: './map.component.html',
  styleUrls: ['./map.component.scss'],
})
export class MapComponent implements OnInit {
  private equipmentService = inject(EquipmentService);

  @Input() markerPositions: IPosition[] | undefined;

  map: LF.Map | undefined;
  center: LF.LatLngExpression = [-15.7801, -47.9292];

  ngOnInit(): void {
    this.initializeMap();
    this.addTileLayer();
    this.subscribeToPositions();
  }

  private initializeMap(): void {
    this.map = LF.map('map').setView(this.center, 6);
  }

  private addTileLayer(): void {
    if (this.map) {
      LF.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(
        this.map
      );
    }
  }

  private subscribeToPositions(): void {
    this.equipmentService.positions.subscribe((positions) => {
      positions.forEach((item) => {
        console.log(item);
        this.addMarker(item);
      });
    });
  }

  private addMarker(equipment: ICustomEquipment): void {
    if (!this.map) return;

    const status = equipment.model.hourlyEarnings.slice(-1)[0].status;
    const icon = this.createCustomIcon(equipment.equipmentModelId);
    const layer = LF.marker(
      [equipment.latestPosition.lat, equipment.latestPosition.lon],
      { icon }
    ).addTo(this.map);

    layer.bindPopup(`
      <b>${equipment.model.name}</b><br>
      Estado atual: ${status!.name}
    `);

    layer.on('mouseover', () => {
      layer.openPopup();
    });

    layer.on('click', () => {
      console.log('Equipamento clicado:', 1);
    });
  }

  private createCustomIcon(equipmentModelId: string): LF.DivIcon {
    const markerHtmlStyles = `
      background-color: ${this.getMarkerColor(equipmentModelId)};
      width: 2rem;
      height: 2rem;
      display: block;
      left: -1.5rem;
      top: -1.5rem;
      position: relative;
      border-radius: 3rem 4rem 0;
      transform: rotate(45deg);
      border: 1px solid #FFFFFF
    `;

    return LF.divIcon({
      className: 'my-custom-pin',
      iconAnchor: [0, 24],
      popupAnchor: [0, -36],
      html: `<span style="${markerHtmlStyles}" />`,
    });
  }

  private getMarkerColor(equipmentModelId: string): string {
    const colorMap: { [key: string]: string } = {
      'a3540227-2f0e-4362-9517-92f41dabbfdf': '#fdcb6e',
      'a4b0c114-acd8-4151-9449-7d12ab9bf40f': '#fd79a8',
      '9c3d009e-0d42-4a6e-9036-193e9bca3199': '#0984e3',
    };

    return colorMap[equipmentModelId] || '#CCCCCC';
  }
}

// src/components/MapComponent.tsx
'use client'

import { useEffect } from 'react'
import 'leaflet/dist/leaflet.css'
import L from 'leaflet'
import dynamic from 'next/dynamic'

interface EquipmentPosition {
  id: string
  name: string
  modelId: string
  position: [number, number]
  currentStatus: string
}

interface MapComponentProps {
  equipmentPositions: EquipmentPosition[]
}

const MapComponent: React.FC<MapComponentProps> = ({ equipmentPositions }) => {
  useEffect(() => {
    const map = L.map('map').setView([0, 0], 2)

    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: '&copy; OpenStreetMap contributors',
    }).addTo(map)

    const getCustomIcon = (modelId: string) => {
      let iconUrl = ''
      switch (modelId) {
        case 'a3540227-2f0e-4362-9517-92f41dabbfdf':
          iconUrl = '/img/caminhaoDeCarga.png'
          break
        case 'a4b0c114-acd8-4151-9449-7d12ab9bf40f':
          iconUrl = '/img/harvester.png'
          break
        case '9c3d009e-0d42-4a6e-9036-193e9bca3199':
          iconUrl = '/img/garraTracadora.png'
          break
        default:
          iconUrl =
            'https://unpkg.com/leaflet@1.7.1/dist/images/marker-icon.png'
      }

      return L.divIcon({
        className: 'custom-icon',
        html: `<div style="
          width: 40px;
          height: 40px;
          border-radius: 50%;
          border: 2px solid #003380;
          overflow: hidden;
          background: white;
        ">
          <img src="${iconUrl}" style="
            width: 100%;
            height: 100%;
            object-fit: cover;
          "/>
        </div>`,
        iconSize: [40, 40],
        iconAnchor: [20, 20],
        popupAnchor: [0, -20],
      })
    }

    equipmentPositions.forEach((equipment) => {
      const popupContent = `
        <div style="text-align: center;">
          <h3>${equipment.name}</h3>
          <p>Status: ${equipment.currentStatus}</p>
          <a href="/equipments/details/${equipment.id}" style="
            display: inline-block;
            padding: 5px 10px;
            background-color: #003380;
            color: white;
            text-decoration: none;
            border-radius: 5px;
          ">Ver mais</a>
        </div>
      `

      L.marker(equipment.position, { icon: getCustomIcon(equipment.modelId) })
        .addTo(map)
        .bindPopup(popupContent)
    })

    if (equipmentPositions.length > 0) {
      const bounds = L.latLngBounds(equipmentPositions.map((e) => e.position))
      map.fitBounds(bounds)
    }

    return () => {
      map.remove()
    }
  }, [equipmentPositions])

  return <div id="map" style={{ height: '100%', width: '100%' }} />
}

export default dynamic(() => Promise.resolve(MapComponent), {
  ssr: false,
})
