// src/components/MapView.vue
<template>
    <div style="height: 600px; width: 800px">
        <l-map
            ref="map"
            v-model:zoom="zoom"
            :center="mapCenter"
            :use-global-leaflet="false"
        >
            <l-tile-layer
                url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                layer-type="base"
                name="OpenStreetMap"
            ></l-tile-layer>

            <l-marker
                v-for="(position, index) in latestPositions"
                :key="index"
                :lat-lng="[position?.lat, position?.lon]"
            >
                <l-popup>
                    Equipamento ID: {{ position?.equipmentId }}<br />
                    Última posição: {{ position?.date }}
                </l-popup>
            </l-marker>
        </l-map>
    </div>
</template>

<script setup lang="ts">
import { ref, computed } from "vue";
import "leaflet/dist/leaflet.css";
import { LMap, LTileLayer, LMarker, LPopup } from "@vue-leaflet/vue-leaflet";
import positionsData from "@/data/equipmentPositionHistory.json";

interface Position {
  date: string;
  lat: number;
  lon: number;
}

interface Equipment {
  equipmentId: string;
  positions: Position[];
}

const zoom = ref<number>(10);

const latestPositions = computed(() => {
    if (positionsData.length > 0) {
        return positionsData.map((equipment: Equipment) => {
            const latestPosition = getLatestPosition(equipment);
            if (latestPosition) {
                return {
                    ...latestPosition,
                    equipmentId: equipment.equipmentId,
                };
            }
            return null;
        });
    } else {
        return [];
    }
});

const mapCenter = computed(() => {
    if (latestPositions.value.length > 0) {
        return latestPositions.value[0];
    } else {
        return [];
    }
});

const getLatestPosition = (equipment: Equipment) => {
    if (equipment.positions && equipment.positions.length > 0) {
        return equipment.positions.reduce((latest, current) => {
            return new Date(current.date) > new Date(latest.date)
                ? current
                : latest;
        }, equipment.positions[0]);
    }
    return null;
};

// onMounted(async () => {
//   fetchPositionHistory()
// });

// async fetchPositionHistory() {
//     try {
//         const response = await fetch("/equipmentPositionHistory.json");
//         console.log('response', response)

//         this.positionsData = await response.json();
//         console.log('positionsData', this.positionsData)
//         this.setLatestPositions();
//     } catch (error) {
//         console.error("Erro ao carregar dados:", error);
//     }
// },
</script>

<style></style>

// src/components/MapView.tsx
import { useEffect, useState } from 'react'
import { MapContainer, TileLayer } from 'react-leaflet'
import EquipmentMarker from './EquipmentMarker'
import EquipmentDetails from './EquipmentDetails'
import type { Equipment, MapViewProps } from '../types/Equipment'
import positionHistory from '../data/equipmentPositionHistory.json'
import { getLatestPosition } from '../utils/dataUtils'
import 'leaflet/dist/leaflet.css'

export default function MapView({ equipmentList }: MapViewProps) {
  const [equipmentWithPosition, setEquipmentWithPosition] = useState<
    Equipment[]
  >([])
  const [selectedEquipmentId, setSelectedEquipmentId] = useState<string | null>(
    null
  )

  useEffect(() => {
    const updatedEquipmentList = equipmentList.map((equipment) => {
      const latestPosition = getLatestPosition(equipment.id, positionHistory)
      return {
        ...equipment,
        position: latestPosition
          ? { lat: latestPosition.lat, lng: latestPosition.lon }
          : equipment.position,
      }
    })

    setEquipmentWithPosition(updatedEquipmentList)
  }, [equipmentList])

  const handleMarkerClick = (equipment: Equipment) => {
    setSelectedEquipmentId(equipment.id)
  }

  return (
    <div style={{ display: 'flex' }}>
      <MapContainer
        center={[-19.1, -46]}
        zoom={11}
        style={{ height: '100vh', width: '100%' }}
      >
        <TileLayer
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
          attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        />
        {equipmentWithPosition.map((equipment) => (
          <EquipmentMarker
            key={equipment.id}
            equipment={equipment}
            onClick={() => handleMarkerClick(equipment)}
          />
        ))}
      </MapContainer>
      {selectedEquipmentId && (
        <div style={{ width: '20%', padding: '20px' }}>
          <EquipmentDetails equipmentId={selectedEquipmentId} />
        </div>
      )}
    </div>
  )
}
