// src/components/Navbar.vue
<template>
  <header>
    <nav class="navbar py-4">
      <div class="container-fluid justify-content-center">
        <div class="brand__test">
          <img src="/img/aiko.png" width="100px" alt="Logo">
        </div>
      </div>
    </nav>
  </header>
</template>

<script>
export default {
  name: "AppNavbar",
  data() {
    return {};
  },
  methods: {},
};
</script>

<style scoped>
header .navbar {
  background: #fff;
  border-bottom: 1px solid #d6deeb;
}
</style>

// src/components/Navbar.tsx
import Image from "next/image";
import Link from "next/link";

export default function Navbar() {
  return (
    <header className="bg-[#FFFFFF]  w-full py-5 border-b border-[#D6DEEB] flex justify-center items-center">
      <div className="xl:max-w-[1092px] w-full mx-14 h-14">
        <Link href="/">
          <Image
            alt="Aiko Logo"
            src="/images/aiko.png"
            width={97}
            height={48}
          />
        </Link>
      </div>
    </header>
  );
}
