// aiko-florestal/src/components/select/index.tsx
/* eslint-disable react-refresh/only-export-components */
import clsx from 'clsx';
import React, { ComponentProps, forwardRef } from 'react';

type SelectFieldProps = {
   placeholder: string;
   options: { value: string; label: string }[];
   errors?: string;
   disabled?: boolean;
   defaultValue?: string;
   className?: string;
} & ComponentProps<'select'>;

const SelectField: React.ForwardRefRenderFunction<HTMLSelectElement, SelectFieldProps> = (
   { placeholder, options, errors, disabled, defaultValue, className, ...props },
   forwardedRef
) => {
   const hasErrors = !!errors;

   return (
      <div>
         <div className='focus-within:border-green-200 focus-within:ring-2 focus-within:ring-green-100 rounded-md'>
            <select
               ref={forwardedRef}
               defaultValue={defaultValue}
               disabled={disabled}
               className={clsx(
                  'block h-10 w-full appearance-none rounded-md border border-gray-400 px-3 py-2 shadow-sm placeholder:text-gray-400 placeholder:text-lg focus:outline-none sm:text-lg',
                  { 'focus:border-primary-400 focus:ring-primary-400': !hasErrors },
                  { 'border-red-500': hasErrors },
                  disabled && 'bg-off-white text-gray-500 cursor-not-allowed',
                  className
               )}
               {...props}
            >
               <option value="" disabled>{placeholder}</option>
               {options.map((option) => (
                  <option key={option.value} value={option.value}>
                     {option.label}
                  </option>
               ))}
            </select>
         </div>
         {hasErrors && <p className="mt-2 text-sm text-red-600">{errors}</p>}
      </div>
   );
};

export default forwardRef(SelectField);

// src/components/Select.vue
<script setup lang="ts">
import { ref, defineProps, defineEmits } from "vue";

interface Option {
  label: string | number | any;
  value: string | number;
}

const props = defineProps<{
  id?: string;
  label?: string;
  options: Option[];
  value?: string | number;
  placeholder?: string;
}>();

const emit = defineEmits(["update:modelValue"]);

const selectedValue = ref<string | number>(props.value || "");

const handleChange = (event: Event) => {
  const target = event.target as HTMLSelectElement;
  selectedValue.value = target.value;
  emit("update:modelValue", selectedValue.value);
};
</script>

<template>
  <div class="my-3">
    <select
      :id="id"
      v-model="selectedValue"
      @change="handleChange"
      :placeholder="placeholder"
      class="border border-[#676767] cursor-pointer text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-[#002087] block w-full p-2.5 bg-white"
    >
      <option v-if="props.label" value="" class="text-[#676767]">
        {{ props.label }}
      </option>
      <option
        v-for="(option, index) in options"
        :key="index"
        :value="option.value"
      >
        {{ option.label }}
      </option>
    </select>
  </div>
</template>
