// app/_components/header.tsx
import Image from "next/image";
import Link from "next/link";

const Header = () => {
    return ( 
        <header className="w-full flex items-center gap-2 py-6 px-5 border-b">
            <Link href={"/"}>
                <Image src="/aiko.png" alt="Logo" width={50} height={50} />
            </Link>
        </header>
     );
}
 
export default Header;

// vue-app/src/pages/home/header.vue
<template>
  <header>
    <div class="flex items-center px-4 py-2 mb-8 border-b row bg-zinc-900 border-zinc-700">
      <img src="@/assets/img/dodo-logo.png" alt="doodo" width="50" />
      <span class="text-xl font-bold text-zinc-200">Dodô</span>
      <span class="text-xl font-bold text-green-700">Agro</span>
      <img src="@/assets/img/aiko.png" alt="aiko" width="50" class="ml-4"/>
    </div>
  </header>
</template>
