// TESTE-FRONTEND-V4/src/components/Header.jsx
import logo from '../assets/aiko.png'
import { Link } from 'react-router-dom'

export default function Header() {
  return (
    <header className="bg-white shadow-md py-4 px-6 flex items-center justify-between">
      <div className="flex items-center">
        <Link to='/'>
          <img src={logo} alt="Aiko Logo" className="h-12" />
        </Link>
      </div>
      <div className="flex items-center">
        <Link to="/equipamentos" className="text-lg font-bold">Equipamentos</Link>
      </div>
    </header>
  )
}

// vue-app/src/pages/home/header.vue
<template>
  <header>
    <div class="flex items-center px-4 py-2 row bg-zinc-900">
      <img src="@/assets/img/dodo-logo.png" alt="doodo" width="50" />
      <span class="text-xl font-bold text-zinc-200">Dodô</span>
      <span class="text-xl font-bold text-green-700">Agro</span>
      <img src="@/assets/img/aiko.png" alt="aiko" width="50" class="ml-4"/>
    </div>
  </header>
</template>
<script lang="ts">
import { defineComponent } from "vue";
export default defineComponent({});
</script>
