// teste-maria-arlyanne/src/components/Map.tsx
import { MapContainer, Marker, Popup, TileLayer } from "react-leaflet";
import "leaflet/dist/leaflet.css";
import { Position } from "../model/position.model";
import { formatDate } from "../util/formatDate";
interface Props {
  data: Array<Position>;
}
export default function Map({ data }: Props) {
  const centerPosition =
    data.length > 0 ? [data[0].lat, data[0].lon] : [-19.126536, -45.947756]; // Fallback: Brasil
  return (
    <MapContainer
      center={centerPosition}
      zoom={10}
      style={{ height: "70vh", width: "70vw" }}
    >
      <TileLayer
        attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
      />
      {data.map((position, index) => (
        <Marker key={index} position={[position.lat, position.lon]}>
          <Popup>
            {position.equipmentModel &&
             <h1>
              {position?.equipmentModel?.name} - {position?.name}{" "}
            </h1>}
            {position?.states != undefined && (
              <>
                <p>
                  Status:
                  <span style={{ color: position?.states[0]?.color }}>
                    {position?.states[0]?.name}
                  </span>
                </p>
              </>
            )}
            <p>Data: {formatDate(new Date(position?.date))}</p>

          </Popup>
        </Marker>
      ))}
    </MapContainer>
  );
}

// components/Equipment/Map.vue
<script setup lang="ts">
interface MapMarker {
  key: string
  name: string
  model: string
  state: string
  lat: number
  lon: number
  date: string
  color: string
}

interface MapProps {
  markers: MapMarker[]
  zoom: number
  hasPath?: boolean
}

const props = defineProps<MapProps>()

const mapPath = computed(() => props.markers.map(({ lat, lon }) => ({ lat, lng: lon })))
</script>

<template>
  <div id="leaflet-map-container">
    <LMap :zoom="props.zoom" :center="[-19.16, -45.95]" :useGlobalLeaflet="false">
      <LTileLayer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" layerType="base" />
      <LCircleMarker
        v-for="marker in props.markers"
        :key="marker.key"
        :latLng="[marker.lat, marker.lon]"
        :color="generateHashColorHex(marker.model)"
        :radius="8"
      >
        <LTooltip>
          <slot name="tooltip" :marker="marker" />
        </LTooltip>
      </LCircleMarker>
      <LPolyline
        v-if="props.hasPath"
        :latLngs="mapPath"
        :color="'gray'"
        :opacity="0.3"
      />
    </LMap>
  </div>
</template>

<style scoped>
#leaflet-map-container {
  height: 60vh;
  width: 100%;
}
</style>
