// components/App/Header.vue
<script setup lang="ts">
</script>

<template>
  <header class="header">
    <NuxtLink to="/">
      <img src="~/assets/aiko.png" alt="logo" />
    </NuxtLink>
    <nav>
      <NuxtLink to="/">Home</NuxtLink>
      <NuxtLink to="/equipments">Equipamentos</NuxtLink>
    </nav>
  </header>
</template>

<style scoped>
.header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  background-color: white;
  padding: 16px;

  img {
    height: 24px;
  }

  nav {
    display: flex;
    gap: 24px;

    a {
      color: rgb(0, 51, 128);
      font-weight: bold;
      text-decoration: none;

      &:hover {
        color: rgb(0, 193, 0);
      }
    }
  }
}
</style>

// TESTE-FRONTEND-V4/src/components/Header.jsx
import logo from '../assets/aiko.png'
import { Link } from 'react-router-dom'

export default function Header() {
  return (
    <header className="bg-white shadow-md py-4 px-6 flex items-center justify-between">
      <div className="flex items-center">
        <Link to='/'>
          <img src={logo} alt="Aiko Logo" className="h-12" />
        </Link>
      </div>
      <div className="flex items-center">
        <Link to="/equipamentos" className="text-lg font-bold">Equipamentos</Link>
      </div>
    </header>
  )
}
