// src/components/Header.vue
<script lang="ts" setup>
import logo from '@/assets/img/aiko.png'
</script>

<template>
  <div class="h-12 w-25 mb-8 self-center">
    <img :src="logo" alt="aiko logo" />
  </div>
  <div class="flex flex-col lg:max-w-full items-center">
    <div class="w-full lg:p-6  rounded-lg shadow-lg text-center max-w-125 lg:max-w-full">
      <h2 class="text-2xl font-bold text-cyan-400 mb-4">Explore os Equipamentos</h2>
      <p class="text-gray-300 text-lg mb-6">
        Clique em um marcador abaixo para exibir informações detalhadas de cada equipamento.
      </p>
    </div>
  </div>
</template>

// TESTE-FRONTEND-V4/src/components/Header.jsx
import logo from '../assets/aiko.png'
import { Link } from 'react-router-dom'

export default function Header() {
  return (
    <header className="bg-white shadow-md py-4 px-6 flex items-center justify-between">
      <div className="flex items-center">
        <Link to='/'>
          <img src={logo} alt="Aiko Logo" className="h-12" />
        </Link>
      </div>
      <div className="flex items-center">
        <Link to="/equipamentos" className="text-lg font-bold">Equipamentos</Link>
      </div>
    </header>
  )
}
