// aiko-front/src/components/Map.vue
<script lang="ts" setup>
import 'leaflet/dist/leaflet.css'
import L from 'leaflet'
import { onMounted } from 'vue'

let map = undefined

const createMapLayer = () => {
  map = L.map('mapContainer').setView([-19.126536, -45.947756], 9)
  L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
  }).addTo(map)
}

onMounted(() => {
  createMapLayer()
})
</script>

<template>
  <div id="mapContainer"></div>
</template>

<style scoped>
#mapContainer {
  height: 1000px;
  width: 1000px;
}
</style>

// teste-maria-arlyanne/src/components/Map.tsx
import { MapContainer, Marker, Popup, TileLayer } from "react-leaflet";
import "leaflet/dist/leaflet.css";
import { Position } from "../model/position.model";
import { formatDate } from "../util/formatDate";
interface Props {
  data: Array<Position>;
}
export default function Map({ data }: Props) {
  const centerPosition =
    data.length > 0 ? [data[0].lat, data[0].lon] : [-19.126536, -45.947756]; // Fallback: Brasil
  return (
    <MapContainer
      center={centerPosition}
      zoom={10}
      style={{ height: "70vh", width: "70vw" }}
    >
      <TileLayer
        attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
      />
      {data.map((position, index) => (
        <Marker key={index} position={[position.lat, position.lon]}>
          <Popup>
            {position.equipmentModel &&
             <h1>
              {position?.equipmentModel?.name} - {position?.name}{" "}
            </h1>}
            {position?.states != undefined && (
              <>
                <p>
                  Status:
                  <span style={{ color: position?.states[0]?.color }}>
                    {position?.states[0]?.name}
                  </span>
                </p>
              </>
            )}
            <p>Data: {formatDate(new Date(position?.date))}</p>

          </Popup>
        </Marker>
      ))}
    </MapContainer>
  );
}
